config/routes.rb
Rails.application.routes.draw do
  get "welcome/index"
  root to: "welcome#index"
  resources :comentarios
  resources :posts
  resources :usuarios

  # Rotas de Login/Logout
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_navbar.html.erb
<% content_for :stylesheets do %>
<%= stylesheet_link_tag "navbar", media: "all" %>
<% end %>


<h1 class="navbar-title">
    <%= link_to "SZBlog", root_path %>
</h1>
<% if usuario_logado? %>
    <nav class="navbar">
        <div class="menu">
            <p> <%= link_to "Usuários", usuarios_path %>
            </p>
            <p> <%= link_to "Comentários", comentarios_path %>
            </p>
            <p> <%= link_to "Posts", posts_path %>
            </p>
        </div>

        <div class="session">
            <p> <%= button_to "Sair", logout_path, method: :delete %> </p>
        </div>
    </nav>
    <% else %>
    <nav class="navbar">
        <div class="session">
            <p> <%= link_to "Criar conta", new_usuario_path %> </p>
            <p> <%= link_to "Login", sessions_new_path %> </p>
        </div>
    </nav>
<% end %>