config/routes.rb
Rails.application.routes.draw do
  get "welcome/index"
  root to: "welcome#index"
  resources :comentarios
  resources :posts
  resources :usuarios

  # Rotas de Login/Logout
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_secure_password
  has_many :posts
  has_many :comentarios
  validates :nome, presence: true
  validates :password, presence: true, on: :create
  validates :password_confirmation, presence: true, on: :create
  validates :email, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :autenticar_usuario!, except: [ :new, :create ]
  before_action :set_usuario, only: %i[ show edit update destroy ]

  # GET /usuarios or /usuarios.json
  def index
    @usuarios = Usuario.all
    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /usuarios/1 or /usuarios/1.json
  def show
    @usuario = Usuario.find(params[:id])
    unless current_usuario == @usuario
      respond_to do |format|
        format.html { redirect_to root_path, alert: "Acesso não autorizado." }
        format.json { render json: { error: "Acesso não autorizado." }, status: :forbidden }
      end
    end
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
    unless current_usuario == @usuario
      redirect_to root_path, alert: "Acesso não autorizado."
    end
  end

  # POST /usuarios or /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        session[:usuario_id] = @usuario.id
        format.html { redirect_to root_path, notice: "Usuário criado com sucesso." }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1 or /usuarios/1.json
  def update
    unless current_usuario == @usuario
      respond_to do |format|
        format.html { redirect_to root_path, alert: "Acesso não autorizado." }
        format.json { render json: { error: "Acesso não autorizado." }, status: :forbidden }
      end
      return
    end

    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: "Usuário atualizado com sucesso." }
        format.json { render json: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1 or /usuarios/1.json
  def destroy
    unless current_usuario == @usuario
      redirect_to root_path, alert: "Acesso não autorizado."
    end
    @usuario.destroy!

    respond_to do |format|
      session[:usuario_id] = nil if current_usuario == @usuario
      format.html { redirect_to root_path, status: :see_other, notice: "Usuário apagado com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:nome, :email, :password, :password_confirmation)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario) do |form| %>
  <% if usuario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(usuario.errors.count, "erro(s)") %> foi encontrado:</h2>

      <ul>
        <% usuario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/usuarios/_usuario.html.erb
<div id="<%= dom_id usuario %>">
  <p>
    <strong>Nome:</strong>
    <%= usuario.nome %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= usuario.email %>
  </p>

</div>

app/views/usuarios/edit.html.erb
<% content_for :title, "Editing usuario" %>

<h1>Editando usuário</h1>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Mostrar usuário", @usuario %> |
  <%= link_to "Voltar para Usuários", usuarios_path %>
</div>

app/views/usuarios/index.html.erb
<% content_for :navbar do %>
    <%= render "shared/navbar" %>
<% end %>

<p><%= notice %></p>

<% content_for :title, "Usuarios" %>

<h1>Usuarios</h1>

<div id="usuarios">
  <% @usuarios.each do |usuario| %>
    <%= render usuario %>
    <p>
      <%= link_to "Mostrar usuário", usuario %>
    </p>
  <% end %>
</div>

app/views/usuarios/new.html.erb
<% content_for :navbar do %>
    <%= render "shared/navbar" %>
<% end %>

<br>
<div>
  <%= link_to "Voltar para Welcome", root_path %>
</div>

<% content_for :title, "New usuario" %>

<h1>New usuario</h1>

<%= render "form", usuario: @usuario %>

<br>

app/views/usuarios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @usuario %>

<div>
    <% if current_usuario == @usuario%>
      <%= link_to "Editar", edit_usuario_path(@usuario) %> |
      <%= link_to "Voltar para Usuários", usuarios_path %>

      <%= button_to "Apagar conta", @usuario, method: :delete %>
    <%elsif%>
      <%= link_to "Voltar para Usuários", usuarios_path %>
    <% end %>
</div>