config/routes.rb
Rails.application.routes.draw do
  get "welcome/index"
  root to: "welcome#index"
  resources :comentarios
  resources :posts
  resources :usuarios

  # Rotas de Login/Logout
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :usuario
  has_many :comentarios, dependent: :destroy

  validates :titulo, presence: true
  validates :texto, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :autenticar_usuario!
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :autoriza_usuario!, only: %i[ edit update destroy ]
  rescue_from ActiveRecord::RecordNotFound, with: :registro_nao_encontrado

  # GET /posts or /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  def new
    @post = Post.new

    respond_to do |format|
      format.html
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_usuario.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post criado com sucesso." }
        format.json { render :show, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post atualizado com sucesso." }
        format.json { render :show, status: :ok }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: "Post apagado com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:titulo, :texto)
    end

    def autoriza_usuario!
      return if @post.usuario == current_usuario

      respond_to do |format|
      format.html { redirect_to root_path, alert: "Acesso não autorizado." }
      format.json { render json: { error: "Acesso não autorizado." }, status: :forbidden }
      end
    end

    def registro_nao_encontrado
      respond_to do |format|
        format.html { redirect_to posts_path, alert: "Post não encontrado." }
        format.json { render json: { error: "Post não encontrado" }, status: :not_found }
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :texto, style: "display: block" %>
    <%= form.textarea :texto %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
    <p>
        <strong>Titulo:</strong>
        <%= post.titulo %>
    </p>

    <p>
        <strong>Texto:</strong>
        <%= post.texto %>
    </p>

    <p>
        <strong>Usuario:</strong>
        <%= post.usuario.nome %>
    </p>

    <%if @post.usuario == current_usuario%>
      <%= button_to "Editar Post", edit_post_path, method: :get %>
      <%= button_to "Apagar Post", posts_path, method: :delete %>
    <%end%>

    <hr>

</div>

app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<% content_for :navbar do %>
<%= render "shared/navbar" %>
<% end %>

<br>
<div>
    <%= link_to "Voltar para Welcome", root_path %>
</div>

<p style="color: green"><%= notice %></p>
<% content_for :title, "Posts" %>

<h1>Posts</h1>

<div id="posts">
    <% @posts.each do |post| %>
    <h4 style="display: inline;">Título: </h4>
    <p style="display: inline;">
        <%= post.titulo %>
    </p>
    <p>
        <%= link_to "Mostrar", post %>
    </p>
    <% end %>
</div>

<%= button_to "Novo Post", new_post_path, method: :get %>

app/views/posts/new.html.erb
<% content_for :title, "New post" %>

<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>



<h3>Comentários:</h3>

<% if @post.comentarios.any? %>
  <% @post.comentarios.each do |comentario| %>
    <div class="comentario_card">
        <p><strong><%= comentario.usuario.nome %></strong> comentou:</p>
        <p><%= comentario.comentario %></p>
          <% if comentario.usuario == current_usuario %>
            <div>
                <%= button_to "Editar comentário", edit_comentario_path(comentario), method: :get %>
                <%= button_to "Apagar comentário", comentario_path(comentario), method: :delete, data: { confirm: "Tem certeza que deseja excluir este comentário?"} %>
            </div>
        <%end%>
        <hr>
    </div>
  <% end %>
<% end %>

<% if @post.comentarios.length == 0 %>
  <div>
      <p>Este Post ainda não recebeu comentário. Seja o primeiro!</p>
  </div>
<% end %>

<%= link_to "Novo comentário", new_comentario_path(post_id: @post.id) %>
<%= link_to "Voltar", posts_path %>